import React, { useEffect, useRef, useState } from 'react'
import jsQR from 'jsqr'
import { X } from 'lucide-react'

/**
 * Scans a QR code via the device camera using jsQR, or accepts a pasted
 * token/payload for demoing without a camera (e.g. scanning the code
 * generated by `generateQr` for another patient on the same screen).
 *
 * Only ever hands back the opaque token string — never patient data —
 * mirroring the backend, which resolves identity only after validating it.
 */
export default function QRScanner({ onScan, onClose }) {
  const videoRef = useRef(null)
  const canvasRef = useRef(null)
  const streamRef = useRef(null)
  const rafRef = useRef(null)
  const [manualValue, setManualValue] = useState('')
  const [cameraError, setCameraError] = useState(null)

  useEffect(() => {
    let cancelled = false

    async function startCamera() {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } })
        if (cancelled) {
          stream.getTracks().forEach((t) => t.stop())
          return
        }
        streamRef.current = stream
        if (videoRef.current) {
          videoRef.current.srcObject = stream
          await videoRef.current.play()
          tick()
        }
      } catch (err) {
        setCameraError('Camera unavailable — use manual entry below instead.')
      }
    }

    function tick() {
      const video = videoRef.current
      const canvas = canvasRef.current
      if (video && canvas && video.readyState === video.HAVE_ENOUGH_DATA) {
        canvas.width = video.videoWidth
        canvas.height = video.videoHeight
        const ctx = canvas.getContext('2d')
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height)
        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
        const code = jsQR(imageData.data, imageData.width, imageData.height)
        if (code && code.data) {
          extractToken(code.data)
          return
        }
      }
      rafRef.current = requestAnimationFrame(tick)
    }

    startCamera()
    return () => {
      cancelled = true
      if (rafRef.current) cancelAnimationFrame(rafRef.current)
      if (streamRef.current) streamRef.current.getTracks().forEach((t) => t.stop())
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function extractToken(raw) {
    // Accept either the full medisight://patient/<token> payload or a bare token.
    const match = raw.match(/medisight:\/\/patient\/(.+)$/)
    const token = match ? match[1] : raw.trim()
    onScan(token)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/70 px-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Scan patient QR code">
      <div className="w-full max-w-sm rounded-3xl bg-white p-5 shadow-lift dark:bg-ink-800">
        <div className="mb-3 flex items-center justify-between">
          <h3 className="text-base font-bold text-ink-900 dark:text-blush-50">Scan patient QR</h3>
          <button onClick={onClose} className="rounded-lg p-1.5 text-ink-400 hover:bg-blush-100 hover:text-ink-700" aria-label="Close scanner">
            <X size={18} />
          </button>
        </div>

        <div className="relative flex aspect-square items-center justify-center overflow-hidden rounded-2xl bg-ink-900">
          {cameraError ? (
            <p className="px-6 text-center text-sm text-ink-300">{cameraError}</p>
          ) : (
            <>
              <video ref={videoRef} className="h-full w-full object-cover" muted playsInline />
              <span className="pointer-events-none absolute inset-8 rounded-2xl border-2 border-white/70" aria-hidden="true" />
            </>
          )}
        </div>
        <canvas ref={canvasRef} className="hidden" />

        <div className="mt-4">
          <label htmlFor="manual-token" className="label text-xs">Or paste the QR token or payload</label>
          <div className="flex gap-2">
            <input
              id="manual-token"
              value={manualValue}
              onChange={(e) => setManualValue(e.target.value)}
              placeholder="medisight://patient/… or raw token"
              className="field"
            />
            <button
              onClick={() => manualValue.trim() && extractToken(manualValue.trim())}
              className="btn-primary rounded-xl"
            >
              Use
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
